# Generated by Django 3.2.23 on 2023-11-12 16:39

import booking.models
import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('Number_of_persons', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default='+44 7814985924', max_length=128, region=None)),
                ('booking_date_and_time', models.DateTimeField(blank=True, null=True, validators=[booking.models.Booking.validate_date])),
            ],
            options={
                'unique_together': {('name', 'phone_number')},
            },
        ),
    ]
